#!/usr/bin/env bash

# All directories are assumed to be in WEBROOT

if [ -z ${CHECK_DIRS+x} ]; then
    CHECK_DIRS=( \
        app/code/local/BlueAcorn \
        app/code/community/BlueAcorn \
    )
fi;

if [ -z ${BLACKLIST_DIRS+x} ]; then
    BLACKLIST_DIRS=( \
    #    app/code/local/BlueAcorn/GreenPistachio
    )
fi;

if [ -z ${CHECK_FILE_EXTS+x} ]; then
    CHECK_FILE_EXTS=( \
        php \
    )
fi;

# per-test defined BASE_BRANCH takes priority over docker run BASE_BRANCH
# which takes priority over default set here
if [ -z ${BASE_BRANCH+x} ]; then
    if [ -z "$BASE_BRANCH" ]; then
        BASE_BRANCH="origin/develop"
    fi
fi;

