<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('sales')->__('Custom Value') ?></h4>
    </div>
    <fieldset>
        <tr>

            <td class="label"><label><strong><?php echo Mage::helper('sales')->__('Custom Value:') ?></strong></label></td>
            <td class="value"><?php echo $this->getOrder()->getIncrementId() ?></td>
        </tr>
    </fieldset>
</div>