<?php $_helper = Mage::helper('blueacorn_cachemanagementmods') ?>
<?php if($_helper->isEnabled()): ?>
<br />
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3><?php echo $this->__('Blue Acorn Controls') ?></h3>
            </td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list blueacorn-management">
    <?php $buttons = $_helper->getButtonList() ?>
    <?php foreach($buttons as $button): ?>
    <tr>
        <td class="scope-label">
            <button
                onclick="setLocation('<?php echo $this->getButtonUrl($_helper->sanitizeLabel($button['label']))?>')"
                type="button"
                class="scalable save">
                <span><?php echo $this->__($button['label']) ?></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo $this->__($button['description'])?>
        </td>
    </tr>
    <?php endforeach ?>
</table>
<?php echo $this->getChildHtml(); ?>
<?php endif ?>