<?php
$quote = $this->getQuote();
$items = $quote->getAllItems();
?>
<div class="page-title">
    <h1><?php echo $this->__('Items in Cart') ?></h1>
</div>
        <form name="transfer_cart" id="transfer_cart"
              action="<?php echo $this->escapeHtml($this->getTransferUrl());?>"
              method="post" style="display: inline-block"
              onsubmit="return confirm('Are you sure you want to submit this form?');">
            <input type="submit" class="button" value="Transfer This Cart" />
        </form>
<?php if (count($items)): ?>
    <table class="data-table" id="manage-wishlist-subaccounts-table">
        <col width="0.2" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th><?php echo $this->__('Product') ?></th>
            <th></th>
            <th><?php echo $this->__('Price') ?></th>
            <th><?php echo $this->__('Qty') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($items as $item): ?>
            <?php if($item->getParentItemId() == null): ?>
                <?php $product = $item->getProduct(); ?>
                <?php $options = $product->getTypeInstance(true)->getOrderOptions($item->getProduct());?>
                <tr>
                    <td><a href="<?php echo $this->escapeHtml($product->getProductUrl()); ?>"><img src="<?php echo (string) Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(150); ?>" alt=""/></a></td>
                    <td><a href="<?php echo $this->escapeHtml($product->getProductUrl()); ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></td>
                    <td><?php echo $this->escapeHtml(Mage::helper('core')->currency($product->getFinalPrice(), true, false)); ?></td>
                    <td><?php echo $this->escapeHtml((float) $item->getQty()); ?></td>
                    <td>
                        <?php if(isset($options['attributes_info'])): ?>
                            <dl>
                                <?php foreach($options['attributes_info'] AS $attribute): ?>
                                    <dt><strong><?php echo $this->escapeHtml($attribute['label'] . ':'); ?></strong></dt>
                                    <dd><?php echo $this->escapeHtml($attribute['value']); ?></dd>
                                <?php endforeach; ?>
                            </dl>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('manage-wishlist-subaccounts-table')</script>
<?php else: ?>
    <p style="padding: 20px;"><?php echo $this->__('No Items in Cart') ?></p>
<?php endif; ?>

<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
        <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>