<?php
$hasNeedApprovalPermission = Mage::helper('cminds_multiuseraccounts')->hasNeedApprovalPermission();
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <?php if ($this->hasCreateOrderPermission()): ?>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Proceed to Checkout')) ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
    <?php endif; ?>
<?php endif?>
<?php if($hasNeedApprovalPermission): ;?>
    <?php if(!$this->cartIsApproved()):; ?>
        <form name="send_for_approve" id="send_for_approve" action="<?php echo $this->getUrl("multiuseraccounts/approve/sendaskforapprove")?>" method="post" style="display: inline-block">
            <input type="submit" class="button" value="send for approval" />
        </form>
    <?php endif; ?>
<?php endif; ?>
