<?php $_orders = $this->getOrders(); ?>
<?php if($_orders->getSize()): ?>
<div class="page-title legacy-orders">
    <h1><?php echo $this->__('My Legacy Orders') ?></h1>
</div>
<?php echo $this->getChildHtml('info');?>
<?php echo $this->getPagerHtml(); ?>
<table class="data-table orders" id="my-legacy-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('Order #') ?></th>
            <th class="date"><?php echo $this->__('Date') ?></th>
            <th class="ship"><?php echo $this->__('Ship To') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th class="status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
            <th class="view">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td class="number"><?php echo $_order->getRealOrderId() ?></td>
            <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
            <td class="a-center view">
                <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-legacy-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php endif ?>
