<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
$searchUrl = Mage::getUrl(
    'amxsearchfront/ajax/index',
    array('_secure'=> Mage::app()->getStore()->isCurrentlySecure())
);

$delay = 500;
if ((string)Mage::getConfig()->getNode('modules/Amasty_Fpc/active') == 'true'
    && Mage::app()->useCache('amfpc')
) {
    $delay = 400;
}

?>
<script type="text/javascript">
    var xsearchObj = new Xsearch({
        url: '<?php echo $searchUrl;?>',
        minChars: '<?php echo Mage::getStoreConfig('amxsearch/autocomplete/min_chars');?>',
        delay: <?php echo $delay;?>,
        selector: '<?php echo Mage::getStoreConfig('amxsearch/theme/selector');?>',
        popupWidth: '<?php echo Mage::getStoreConfig('amxsearch/autocomplete/width');?>'
    });
</script>
