(function($) {
    // Data from the CSV generated by Node script (array of objects)
    var data = [];

    // Instantiate the constructor
    var BA_GAQ = new GaqTracker(data);

    BA_GAQ.setMode('universal');

    // Run the tracking AFTER doc ready
    $(document).ready(function() {

        /* -------------------------- *\
         *     MAIN AUTOTRACKING      *
        \* -------------------------- */
        BA_GAQ.trackAll();

        /* ------------------------- *\
         *      MANUAL TRACKING      *
        \* ------------------------- */

    }); // end doc ready

}(jQuery));
