<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattr
 */
?>
<?php //avoid duplication
    if(!Mage::registry('onepage_repeated_data')) :?>
<?php Mage::register('onepage_repeated_data', true)?>

<style>
#amorderattr .required
{
    color: #EB340A;
}

#amorderattr label {
    margin: 0;
}

#amorderattr .field-row {
    margin-bottom: 10px;
}

#td_review{
    padding-left: 35px;
}

.checkboxes li label,
.radios li label {
    font-weight: normal;
}

.checkboxes input,
.radios input {
    float: left; 
    margin-right: 5px;
    position: relative;
    top: 2px;
}
.tooltipicon {
    display: inline-block;
}
.tooltipicon img {
    height: 20px;
    width: 20px;
}
.tooltip{
    width: auto;
    height: auto;
    border: 1px solid rgba(59, 59, 59, 0.45);
    border-radius: 5px;
    color: rgba(0, 0, 0, 0.39);
    display: none;
    text-align: center;
}
</style>

<script type="text/javascript">

    //var h = new Hash();
    Validation.addAllThese([
        ['validate-checkboxgroup-required', 'Please select an option.', function(v, elm) {
            id = elm.id.slice(0, elm.id.lastIndexOf("_"));
            /*if (h.get(id)) {
                return true;
            }*/
            //h.set(id, true);
            checkboxGroupChecked = false;
            $$('input[id^=' + id + ']').each(function(checkbox){
                if (checkbox.checked || jQuery(checkbox).hasClass('validation-failed'))
                {
                    checkboxGroupChecked = true;
                }
            });
            return checkboxGroupChecked;
        }],
        
        ['validate-length-less-25', 'Please use the value with length less or equal than 25 characters', function(v) {
            return v.length <= 25;
        }]
    ]);
    function clearHash() {
        h = new Hash();
    }
    $$('#checkoutSteps button').each(function(button){
        button.observe('click', clearHash);
    });
    
    var amOrderattrConditionObj = new amOrderattrCondition({
        'shipping_methods': <?php print Mage::helper('core')->jsonEncode($this->getShippingMethods());?>
    });
    
    amOrderattrConditionObj.check();
</script>

<script>
    window.org_alert = window.alert; // save original function
    window.alert = null; // disable alerts
</script>

<?php // ajax  strips <script> from response so populate it in advance
$block = Mage::app()->getLayout()->createBlock('amorderattr/fields')->setStep('review');
$elementsHtml = '';
foreach ($block->getFormElements() as $element) {
    $elementsHtml .= $element->toHtml();
}
$dom = new DOMDocument();
$dom->loadHTML($elementsHtml);
$scripts = $dom->getElementsByTagName('script');
foreach ($scripts as $index => $row) {
    echo '<script type="text/javascript">' . $row->nodeValue . '</script>';
}
?>

<script>
    window.alert = window.org_alert; //restore alerts
</script>

<?php endif; //end onepage repeated data?>


<?php if ('review' == $this->getStep()):?>
<?php Mage::unregister('onepage_repeated_data'); ?>
     <tr>
        <td colspan='4' id="td_review">
            <form id="form_review">
 <?php endif; ?>

<ul class="form-list">
    <?php foreach ($this->getFormElements() as $element): ?>
    <li class="fields">
        <div class="input-box">
        <?php
            echo $element->toHtml();
        ?>
        </div>
    </li>
    <?php endforeach; ?>
</ul>

<?php if ('review' == $this->getStep()):?>
        </form>
    </td>
 </tr>
 <?php endif;?>
