<?php
/**
 * Copyright (c) 2013 S.L.I. Systems, Inc. (www.sli-systems.com) - All Rights Reserved
 * This file is part of Learning Search Connect.
 * Learning Search Connect is distribute under license,
 * go to www.sli-systems.com/LSC for full license details.
 *
 * THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
 * PARTICULAR PURPOSE.
 * 
 * Javascript that provides functionality to run the SLI feed generator using
 * ajax.
 *
 * @package SLI
 * @subpackage Search
 */
?>
<script type="text/javascript">
//<![CDATA[

    var sliSearch = {
        isInit : false,
        buttonId : null,
        init : function() {
            this.url = '<?php echo $this->getGenerateUrl() ?>';
            this.buttonId = '<?php echo $this->getButtonId()?>';
            this.displayId = "sli_display_msg";
            this.isInit = true;
        },
        generateFeed : function() {
            if (!this.isInit) {
                this.init();
            }
            new Ajax.Request(this.url, {
                onSuccess: function(transport) {
                    var response = transport.responseText.evalJSON();
                    this.displayResults(response);
                }.bind(this)
            });
        },
        displayResults : function(response) {
            var responseEl = $(this.displayId);
            if (responseEl == null) {
                var responseEl = new Element('p', {id : this.displayId}).addClassName('note');
                Element.insert($(this.buttonId) , {after: responseEl});
            }
            if(response.messages) {
                responseEl.innerHTML = '';
                for(var message in response.messages) {
                    responseEl.appendChild( new Element('p').update('<b>' + message + ':</b> ' + response.messages[message]));
                }
                return responseEl;
            }
            if (response.error) {
                return responseEl.innerHTML = response.error;
            }
            $(this.buttonId).disabled = true;
            $(this.buttonId).addClassName("disabled");
            return responseEl.innerHTML = "<?php echo Mage::getModel('sli_search/feed')->getAjaxNotice(); ?>";
        }
    }

//]]>
</script>