<?php
	$_item = $this->getItem();
	$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
	$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item" xmlns="http://www.w3.org/1999/html">
	<?php if ( $this->hasProductUrl() ): ?>
		<a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(59, 59)->setWatermarkSize('30x10'); ?>" width="59" height="59" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
	<?php else: ?>
		<span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(59, 59)->setWatermarkSize('30x10'); ?>" width="59" height="59" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
	<?php endif; ?>
	<div class="product-details">
		<p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
		
		<table class="info-wrapper">
			<tbody>
				<tr>
					<td class="item-qty"><span class="label"><?php echo $this->__('Qty'); ?>:</span>&nbsp;<span><?php echo $this->getQty(); ?></span></td>
					<td>
						<?php if ( $canApplyMsrp ): ?>
							<span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
						<?php else: ?>
						
						<?php if ( $this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices() ): ?>
							<?php if ( $this->helper('tax')->displayCartBothPrices() ): ?>
								<?php echo $this->__('Excl. Tax'); ?>:
							<?php endif; ?>
							<?php if ( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') ): ?>
								<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
							<?php else: ?>
								<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
							<?php endif; ?>
							<?php if ( Mage::helper('weee')->getApplied($_item) ): ?>
								<br />
								<?php if ( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') ): ?>
								<small>
									<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
										<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
									<?php endforeach; ?>
								</small>
								<?php elseif ( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') ): ?>
								<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
									<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
								<?php endforeach; ?>
								<?php elseif ( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') ): ?>
								<small>
									<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
										<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
									<?php endforeach; ?>
								</small>
								<?php endif; ?>
								<?php if ( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') ): ?>
								<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
								<?php endif; ?>
							<?php endif; ?>
						<?php endif; ?>
						
						<?php if ( $this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices() ): ?>
							<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
							<?php if ( $this->helper('tax')->displayCartBothPrices() ): ?>
								<br /><?php echo $this->__('Incl. Tax'); ?>:
							<?php endif; ?>
							<?php if ( Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') ): ?>
								<?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
							<?php else: ?>
								<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
							<?php endif; ?>
							<?php if ( Mage::helper('weee')->getApplied($_item) ): ?>
								<br />
								<?php if ( Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') ): ?>
								<small>
									<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
										<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
									<?php endforeach; ?>
								</small>
								<?php elseif ( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') ): ?>
								<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
									<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span>
								<?php endforeach; ?>
								<?php elseif ( Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') ): ?>
								<small>
									<?php foreach ( Mage::helper('weee')->getApplied($_item) as $tax ): ?>
										<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
									<?php endforeach; ?>
								</small>
								<?php endif; ?>
								<?php if ( Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') ): ?>
								<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
								<?php endif; ?>
							<?php endif; ?>
						<?php endif; ?>
						
						<?php endif; //Can apply MSRP ?>
					</td>
				</tr>
			</tbody>
		</table>
		
		<?php $__orderOptions = $_item->getProduct()->getTypeInstance(true)->getOrderOptions($_item->getProduct()); ?>
		<?php if ( $_options = $__orderOptions['attributes_info'] ): ?>
			<div class="truncated">
				<div class="truncated_full_value">
					<dl class="item-options">
					<?php foreach ($_options as $_option) : ?>
					<dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
					<dd>
						<?php if ( is_array($_option['value']) ): ?>
						<?php echo nl2br(implode("\n", $_option['value'])) ?>
						<?php else: ?>
						<?php echo $_option['value'] ?>
						<?php endif; ?>
					</dd>
					<?php endforeach; ?>
					</dl>
				</div>
				<a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
			</div>
		<?php endif; ?>
		
		<div class="description">
			<?php if ( $_item->getProduct()->isAvailable() ): ?>
				<?php $__strLeadTime = Mage::getResourceModel('catalog/product')->getAttributeRawValue($_item->getProductId(), 'lead_time', Mage::app()->getStore()->getId()); ?>
				<?php
					$__optionValue = Mage::getResourceModel('catalog/product')->getAttributeRawValue($_item->getProductId(), 'stock', Mage::app()->getStore()->getId());
					$__productInstance = Mage::getModel('catalog/product')
						->setStoreId(Mage::app()->getStore()->getId())
						->setData('stock', $__optionValue)
					; 
					$__optionLabel = $__productInstance->getAttributeText('stock');
				?>
				<span><?php
					echo "This item ";
					switch ( $__optionLabel ):
						case "Stock Item":
							echo "ships from our warehouse; ";
						break;
						case "Factory Stock Item":
							echo "ships from the manufacturer; ";
						break;
						case "Made to Order":
							echo "is custom made and ships from the manufacturer; ";
						break;
						default:
							echo "";
					endswitch;
					?>departs in <?php echo $__strLeadTime ?>.
				</span>
			<?php endif; ?>
		</div>
	</div>
</li>