<div class="summary-totals" id="summary-totals">
	<table id="summary-totals-table">
		<colgroup>
			<col>
			<col width="1">
		</colgroup>
		<tbody>
			<tr>
				<td style="" class="a-left" colspan="1"><?php echo $this->__('Subtotal'); ?></td>
				<td style="" class="a-right">
					<span class="price"><?php echo $this->getSubtotal(); ?></span>
				</td>
			</tr>
			<tr>
				<td style="" class="a-left" colspan="1"><?php echo $this->__('Shipping'); ?></td>
				<td style="" class="a-right">
					<span class="price" id="summary-shipping"><?php echo $this->getShippingAmount(); ?></span>
				</td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td style="" class="a-left" colspan="1">
					<strong><?php echo $this->__('Grand Total'); ?></strong>
				</td>
				<td style="" class="a-left">
					<strong><span class="price" id="summary-grand-total"><?php echo $this->getGrandTotal(); ?></span></strong>
				</td>
			</tr>
		</tfoot>
	</table>
</div>