<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_List
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_lists = $this->getLists(); ?>
<div class="page-head"> 
    <h3><?php echo $this->__('My Favorites') ?></h3>
</div>
<?php if(sizeof($_lists->getItems()) > 0 ): ?>
    <table cellspacing="0" class="data-table" id="my-lists-table">
        <col width="80%"/>
        <col width="20%"/>
        <thead>
            <tr>
                <th><?php echo $this->__('Folder') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
            <?php foreach ($_lists as $row): ?>
                <tr class="<?php echo ($_odd = ($_odd ? 'odd' : '')) ?>">
                    <td><a href="<?php echo $this->getUrl('*/*/order', array('id'=>$row->getId()))?>"><?php echo $this->htmlEscape($row->getTitle()) ?></a></td>
                    <td class="last a-center">
                        <button onclick="setLocation('<?php echo $this->getUrl('*/*/order', array('id'=>$row->getId())) ?>')" class="button" type="button"><span>Order</span></button>
                        <?php if($this->helper('amlistl')->isImportExportAllowed()): ?>
                            <a href="<?php echo $this->getUrl('*/*/edit', array('id'=>$row->getId()))?>"><?php echo $this->__('Edit Guide') ?></a><br />
                            <a class="link-remove" href="<?php echo $this->getUrl('*/*/remove', array('id'=>$row->getId()))?>"  onclick="return confirm('<?php echo $this->__('Are you sure?') ?>')" ><?php echo $this->__('Remove') ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-lists-table')</script>
<?php else: ?>
    <p><?php echo $this->__('Fill in your favorites products to be able to purchase all of them with one click!'); ?></p>
<?php endif; ?>
<?php if($this->helper('amlistl')->isImportExportAllowed()): ?>
<div class="buttons-set">    
       <form id="exportFavoriteProductsForm" action="<?php echo $this->getUrl('*/*/exportCsv') ?>" method="post">
                <button class="button" type="submit"><span><?php echo $this->__('Export CSV') ?></span></button>
	</form>
	<form id="importFavoriteProductsForm" action="<?php echo $this->getUrl('*/*/importCsv') ?>" method="post" enctype="multipart/form-data">
		<button class="button" type="button"><span><?php echo $this->__('Import CSV') ?></span></button>
		<input type="file" name="file" onChange="document.getElementById('importFavoriteProductsForm').submit()"><br>
	</form>
</div>    
<?php endif; ?>
