<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_List
 */
?>
<?php $_list = $this->getList(); ?>
<?php $items = $this->getList()->getItems(); ?>
<?php $_hlp = Mage::helper('amlist'); ?>
<?php $_coreHelper = $this->helper('core'); ?>
<h3><?php echo $this->htmlEscape($_list->getTitle()) ?></h3>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if (count($items)): ?>
<form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
<input type="hidden" name="list_id" value="<?php echo $this->getList()->getId() ?>">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="buttons-set">
        <a href="<?php echo $this->getUrl('*/*/index') ?>" class="left">&laquo; <?php echo $this->__('All Folders') ?></a>
        <button type="submit" onclick="this.form.action='<?php echo $this->getUrl('*/*/mrscart') ?>'" class="button" type="button"><span><?php echo $this->__('Add to Cart') ?></span></button>
    </div>
    <div class="paging"></div>
    <table cellspacing="0" width="100%" class="data-table box-table" id="amlist-table">    <col width="30" />
        <col width="60" />
        <col />
        <col width="120" />
        <col width="60" />
        <col />
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>SKU</th>
                <th><?php echo $this->__('Details') ?></th>
                <th><?php echo $this->__('Price') ?></th>
                <th><?php echo $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php 
            $allLists = $this->getAllLists($this->getList()->getId()); 
            $total    = 0;
        ?>
        <?php foreach ($items as $item): $id = $item->getId();?>
            <tr>
                <td>
                        <a href="<?php echo $this->getProductItemUrl($item) ?>">
                            <img src="<?php echo $this->getProductItemImage($item)  ?>"
                                 alt="<?php echo $this->htmlEscape($item->getProduct()->getName()) ?>" width="50" style="width:50px;" />
                        </a>
                </td>
                <td><?php echo $item->getProduct()->getSku(); ?></td>
                <td>
                        <a href="<?php echo $this->getProductItemUrl($item) ?>"
                           title="<?php echo $this->htmlEscape($item->getProduct()->getName()) ?>">
                            <?php echo $this->htmlEscape($item->getProduct()->getName()) ?>
                        </a><br />
                        Case Pack: <?php echo $item->getProduct()->getAttributeText('uom'); ?>
                    <?php echo $item->getOptionsHtml() ?>
                    <?php if(!$item->getProduct()->isSaleable()){ $unsaleable = true; ?><span class="availability out-of-stock">Product is currently not available.</span> <?php }else{$unsaleable= false;} ?>
                </td>
                <td>
                    <?php $price = $item->getPrice(); $total += ($price * $item->getQty());  echo $_coreHelper->formatPrice($price, true); ?>
                </td>
                <td>
                    <input type="text" size="2" name="qty[<?php echo $id ?>]" value="" class="input-text"<?php if($unsaleable){echo " disabled" ; } ?> />
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <div class="paging"></div>
    <div class="buttons-set">
        <a href="<?php echo $this->getUrl('*/*/index') ?>" class="left">&laquo; <?php echo $this->__('All Folders') ?></a>
        <button type="submit" onclick="this.form.action='<?php echo $this->getUrl('*/*/mrscart') ?>'" class="button" type="button"><span><?php echo $this->__('Add to Cart') ?></span></button>
    </div>
</form>
<script type="text/javascript">decorateTable('amlist-table')</script>
<?php else: ?>
    <?php if ($this->getList()->getId()): ?>
    <p><?php echo $this->__('Start adding items from the <a href=""%s"">catalog</a> to your favorites right now!', Mage::getBaseUrl())?></p>
    <?php endif; ?>
    <div class="button-set">
        <a href="<?php echo $this->getUrl('*/*/index') ?>" class="left">&laquo; <?php echo $this->__('All Folders') ?></a> 
    </div>
<?php endif ?>
<script type="text/javascript" src="/skin/frontend/blueacorn/partners/js/datatable.min.js"></script>
<script type="text/javascript" src="/skin/frontend/blueacorn/partners/js/datatable.jquery.js"></script>
<script type="text/javascript">
    $j(document).ready(function () {
        $j("#ckbCheckAll").click(function () {
            $j(".checkBoxClass").prop('checked', $j(this).prop('checked'));
        });

        $j("#amlist-table").datatable({
            pageSize: 20,
            sort: [false, true, true, true, false, false]
        }) ;
    });
</script>