<?php
/**
 * Created by PhpStorm.
 * User: justinsimon
 * Date: 3/18/16
 * Time: 3:40 PM
 */
?>

<script type="text/javascript">
  var gts = gts || [];

  gts.push(["id", "692366"]);
  gts.push(["badge_position", "BOTTOM_RIGHT"]);
  gts.push(["locale", "en_US"]);

  (function() {
      var gts = document.createElement("script");
      gts.type = "text/javascript";
      gts.async = true;
      gts.src = "https://www.googlecommerce.com/trustedstores/api/js";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(gts, s);
  })();
</script>